DROP TABLE IF EXISTS users4;
DROP TABLE IF EXISTS books;
DROP SEQUENCE IF EXISTS global_se4;
DROP SEQUENCE IF EXISTS global_se6;

CREATE SEQUENCE global_se4 START 10000;
CREATE SEQUENCE global_se6 START 10000;

CREATE TABLE users4(
  userid INTEGER PRIMARY KEY DEFAULT nextval('global_se4'),
  firstname VARCHAR NOT NULL,
  lastname VARCHAR NOT NULL,
  city VARCHAR NOT NULL,
  tel INTEGER NOT NULL,
  dob DATE DEFAULT NULL,
  email VARCHAR NOT NULL
);

CREATE TABLE books(
  bookid INTEGER PRIMARY KEY DEFAULT nextval('global_se6'),
  userid INTEGER NOT NULL,
  author VARCHAR NOT NULL,
  title VARCHAR NOT NULL,
  genre VARCHAR NOT NULL,
 /* FOREIGN KEY (userid) REFERENCES users4(userid) ON DELETE CASCADE*/
);